#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.11.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

pull_requests:
  do_not_increment_build_number: true

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- ps: .\build.ps1

test: off
deploy: off

#---------------------------------#
#       R# Command Line Tools     #
#---------------------------------#

install:
- cmd: choco install resharper-clt --version 2018.1.3

after_build:
- cmd: InspectCode.exe .\BenchmarkDotNet.sln --project=BenchmarkDotNet -o=resharper-clt-output.xml
- ps: $result = [xml](Get-Content .\resharper-clt-output.xml)
- ps: $result.Report.Issues.ChildNodes | ForEach-Object {$project = $_.Name; $_.ChildNodes | ForEach-Object {Add-AppveyorCompilationMessage -Category Error -Message $_.Message -Line $_.Line -FileName $_.File -ProjectName $project}}

artifacts:
  - path: '**\BenchmarkDotNet.*.nupkg' # find all NuGet packages recursively
  - path: 'resharper-clt-output.xml'